project_id = "epovugflrajgaikfwdgq"

[functions.hubtel-initiate]
verify_jwt = false

[functions.hubtel-callback]
verify_jwt = false

[functions.donation-metrics]
verify_jwt = false

[functions.verify-admin-password]
verify_jwt = false

[functions.hubtel-verify]
verify_jwt = false
